"""Rebuild the gallery photo list from whatever is in the /gallery folder.

HOW TO ADD PHOTOS TO THE WEBSITE
  1. Copy your photos into the  gallery  folder (jpg, jpeg, png or webp).
  2. Double-click this file, or run:   python add_photos.py
  3. Commit and push. The new photos appear on the Gallery page.

Photos are sorted by filename, so naming them 01-..., 02-... controls the order.
Anything in gallery/captions.txt of the form  filename = caption  is used as the
caption under that photo.
"""
import io
import os
import json

HERE = os.path.dirname(os.path.abspath(__file__))
GALLERY = os.path.join(HERE, 'gallery')
OUT = os.path.join(HERE, 'gallery-photos.js')
EXT = ('.jpg', '.jpeg', '.png', '.webp')

def main():
    if not os.path.isdir(GALLERY):
        os.makedirs(GALLERY)
        print('Created the gallery folder. Put your photos in it and run this again.')
        return

    captions = {}
    cap_file = os.path.join(GALLERY, 'captions.txt')
    if os.path.isfile(cap_file):
        for line in io.open(cap_file, encoding='utf-8'):
            if '=' in line and not line.strip().startswith('#'):
                k, v = line.split('=', 1)
                captions[k.strip()] = v.strip()

    files = sorted(f for f in os.listdir(GALLERY) if f.lower().endswith(EXT))
    photos = [{'src': 'gallery/' + f, 'caption': captions.get(f, '')} for f in files]

    body = ',\n'.join(
        '  { src: %s, caption: %s }' % (json.dumps(p['src']), json.dumps(p['caption']))
        for p in photos
    )
    js = (
        '/* Gallery photo list.\n'
        '   Generated by add_photos.py from the /gallery folder.\n'
        '   Add photos to that folder and run:  python add_photos.py  */\n\n'
        'const GALLERY_PHOTOS = [\n' + body + '\n];\n'
    )
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(js)
    print('Found %d photo(s). Updated gallery-photos.js' % len(photos))
    for f in files:
        print('   ', f)

if __name__ == '__main__':
    main()
