/* Gallery photo list.
   Generated by add_photos.py from the /gallery folder.
   Add photos to that folder and run:  python add_photos.py  */

const GALLERY_PHOTOS = [
  { src: "gallery/1.jpeg", caption: "" },
  { src: "gallery/2.jpeg", caption: "" },
  { src: "gallery/3.jpeg", caption: "" },
  { src: "gallery/5.jpeg", caption: "" },
  { src: "gallery/6.jpeg", caption: "" },
  { src: "gallery/7.jpeg", caption: "" },
  { src: "gallery/8.jpeg", caption: "" },
  { src: "gallery/9.jpeg", caption: "" },
  { src: "gallery/alflornlift.jpg", caption: "" },
  { src: "gallery/alfnlorna.jpg", caption: "" },
  { src: "gallery/alfnlorna2.jpg", caption: "" },
  { src: "gallery/alfnlorna3.jpg", caption: "" },
  { src: "gallery/alfnlornalegs.jpg", caption: "" }
];
